version: '3.8'
services:
  app:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
    volumes:
      - .:/app:cached
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}